
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author chris
 */
public class ColorGame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ColorGame() {
        initComponents();

        ActionListener task = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jLabel4.setText(String.valueOf(time));
                time--;
                if (time == 0) {
                    jLabel4.setText(String.valueOf(time));
                    timeOutGame();
                    timer.stop();
                }
            }
        };
        timer = new Timer(0, task);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Red");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Orange");
        jButton2.setEnabled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 51));
        jButton3.setText("Yellow");
        jButton3.setEnabled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setBackground(new java.awt.Color(0, 184, 41));
        jButton4.setForeground(new java.awt.Color(0, 184, 41));
        jButton4.setText("Green");
        jButton4.setEnabled(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Blue");
        jButton5.setEnabled(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(215, 0, 255));
        jButton6.setForeground(new java.awt.Color(215, 0, 255));
        jButton6.setText("Purple");
        jButton6.setEnabled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(107, 63, 0));
        jButton7.setForeground(new java.awt.Color(107, 63, 0));
        jButton7.setText("Brown");
        jButton7.setEnabled(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 150, 255));
        jButton8.setForeground(new java.awt.Color(255, 150, 255));
        jButton8.setText("Pink");
        jButton8.setEnabled(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton8);

        jPanel3.setLayout(new java.awt.GridLayout(5, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Score: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Highscore: ");
        jPanel3.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("60");
        jPanel3.add(jLabel4);

        jButton9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton9.setText("Start Game");
        jButton9.setPreferredSize(new java.awt.Dimension(30, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JButton clicked = (JButton) evt.getSource();
        if (clicked.getText().equals(jLabel1.getText())) {
            nextbutt();
            scorePlus();
        } else {
            int temp;
            temp = score;
            timer.stop();
            JOptionPane.showMessageDialog(null, "Wrong button! Game over.\nFinal Score: " + temp);
            nxt = 100;
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(true);
            if (highScore < score) {
                setHighScore();
                setHighScoreName();
            }

        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        findHighScore();
        findHighScoreName();
        jLabel3.setText(String.valueOf("Highscore: " + highScore + " " + name));
        nextbutt();
        nxt = 0;
        score = 0;
        time = 60;
        jLabel2.setText("Score: " + String.valueOf(score));
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(false);

        timer.restart();
        timer.setDelay(1000);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void nextbutt() {
        if (nxt == 100) {
        } else {
            switch (generate()) {
                case 0:
                    jLabel1.setText(jButton1.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                case 1:
                    jLabel1.setText(jButton2.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                case 2:
                    jLabel1.setText(jButton3.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                case 3:
                    jLabel1.setText(jButton4.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                case 4:
                    jLabel1.setText(jButton5.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                case 5:
                    jLabel1.setText(jButton6.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                case 6:
                    jLabel1.setText(jButton7.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                case 7:
                    jLabel1.setText(jButton8.getText());
                    jLabel1.setForeground(colorGen());
                    break;
                default:
                    break;
            }
        }

    }

    private Color colorGen() {
        int color;
        Random r = new Random();
        color = r.nextInt(8);
        switch (color) {
            case 0:
                return jButton8.getForeground();
            case 1:
                return jButton7.getForeground();
            case 2:
                return jButton6.getForeground();
            case 3:
                return jButton5.getForeground();
            case 4:
                return jButton4.getForeground();
            case 5:
                return jButton3.getForeground();
            case 6:
                return jButton2.getForeground();
            case 7:
                return jButton1.getForeground();
            default:
                break;
        }
        return null;
    }

    private void scorePlus() {
        score++;
        jLabel2.setText("Score: " + score);
    }

    private int generate() {
        Random r = new Random();
        nxt = r.nextInt(8);
        return nxt;

    }

    private void findHighScore() {
        try (FileReader fr = new FileReader("hs.txt")) {
            BufferedReader br = new BufferedReader(fr);
            String grab = br.readLine();
            highScore = Integer.parseInt(grab);
            fr.close();
            br.close();

        } catch (FileNotFoundException ex) {
            System.out.println("Could not find the file " + ex.getMessage());
        } catch (IOException ex) {
            System.out.println("Could not find the file " + ex.getMessage());
        }
    }

    private void findHighScoreName() {
        try (FileReader fr = new FileReader("hsn.txt")) {
            BufferedReader br = new BufferedReader(fr);
            name = br.readLine();
            fr.close();
            br.close();

        } catch (FileNotFoundException ex) {
            System.out.println("Could not find the file " + ex.getMessage());
        } catch (IOException ex) {
            System.out.println("Could not find the file " + ex.getMessage());
        }
    }

    private void setHighScore() {
        try {
            PrintWriter pw = new PrintWriter("hs.txt");
            pw.print(String.valueOf(score));
            pw.close();
        } catch (FileNotFoundException ex) {
            System.out.println("There ws an error writing the file " + ex.getMessage());
        }
    }

    private void setHighScoreName() {
        try {
            PrintWriter pw = new PrintWriter("hsn.txt");
            name = JOptionPane.showInputDialog("Congratulations! You set a new high score!\nEnter your name.");
            pw.print(name);
            pw.close();
        } catch (FileNotFoundException ex) {
            System.out.println("There ws an error writing the file " + ex.getMessage());
        }
    }

    private void timeOutGame() {
        timer.stop();
        JOptionPane.showMessageDialog(null, "Times up!\nYour score is: " + score);
        nxt = 100;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(true);
        setHighScore();
        if (highScore < score) {
            setHighScore();
            setHighScoreName();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorGame().setVisible(true);
            }
        });
    }
    String name;
    Timer timer;
    int time = 59;
    private int nxt = 0;
    private int score = 0;
    private int highScore = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
